name: Deploy multi-k8s

on:
  push:
    branhes:
      - main

env:
  SHA: ${{ github.sha }}

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login (Docker Hub)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Test (client)(client)
        run: |
          docker build -t react-test -f ./client/Dockerfile.dev ./client
          docker run --rm -e CI=true react-test npm test

          docker build -t react-test -f ./client/Dockerfile.dev ./client
          docker run --rm -e CI=true react-test npm test

      # Установим gcloud и авторизуемся ключом сервис-аккаунта
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Подтянуть kube-credentials для GKE
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}     # напр. multi-k8s
          location: ${{ secrets.GCP_REGION }}          # напр. us-central1 (регион для Autopilot)
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Собираем три образа с двумя тегами: :latest и :SHA
      - name: Build images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      # Публикуем оба тега каждого образа
      - name: Push images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-client:${{ env.SHA }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-server:${{ env.SHA }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:${{ env.SHA }}

      # Применяем все манифесты и принудительно переключаем деплойменты на образы с тегом SHA
      - name: Apply k8s and set images
        run: |
          kubectl apply -f k8s
          kubectl set image deployment/server-deployment  server=${{ secrets.DOCKERHUB_USERNAME }}/multi-server:${{ env.SHA }}
          kubectl set image deployment/client-deployment  client=${{ secrets.DOCKERHUB_USERNAME }}/multi-client:${{ env.SHA }}
          kubectl set image deployment/worker-deployment  worker=${{ secrets.DOCKERHUB_USERNAME }}/multi-worker:${{ env.SHA }}